# Generated by Django 4.2.10 on 2024-08-15 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_image', models.ImageField(upload_to='categories/')),
                ('display_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther_name', models.CharField(max_length=50)),
                ('testimonial_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('is_available_offline', models.BooleanField(default=False)),
                ('happy_sessions', models.IntegerField(default=453)),
                ('slot_duration', models.CharField(choices=[('30min', '30min'), ('40min', '40min')], default='30min', max_length=30)),
                ('session_fees', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address', models.CharField(max_length=120)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='therapists/')),
                ('educational_qualification', models.CharField(max_length=60)),
                ('categories', models.ManyToManyField(to='therapist.category')),
                ('language', models.ManyToManyField(to='therapist.language')),
                ('testimonial', models.ManyToManyField(to='therapist.testimonial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
