# Generated by Django 4.2.10 on 2024-08-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='address',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
