# Generated by Django 4.2.10 on 2024-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_alter_therapist_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='slot_duration',
            field=models.CharField(choices=[('30min', '30'), ('40min', '40')], default='30min', max_length=30),
        ),
    ]
