# Generated by Django 4.2.10 on 2024-08-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0006_alter_therapist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='user',
        ),
    ]
