# Generated by Django 4.2.10 on 2024-08-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
