# Generated by Django 4.2.10 on 2024-08-18 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_alter_therapist_address'),
        ('availability', '0002_alter_availability_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='therapist.therapist'),
        ),
    ]
