# Generated by Django 4.2.10 on 2024-08-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_bookings_payment_status_bookingpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
