# Generated by Django 4.2.10 on 2024-08-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookings_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
