# Generated by Django 4.2.10 on 2024-08-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookings_meet_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='therapist_name',
            new_name='therapist',
        ),
    ]
